services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ~/home/baptiste/data:/var/www/html
      - ./web:/var/www/html
    networks:
      - inception
  wordpress:
    build: requirements/wordpress/.
    container_name : wordpress
    depends_on:
      - mariadb
    volumes:
      - ~/home/baptiste/data:/var/www/html
      - ./web:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ~/home/baptiste/data:/var/lib/mysql
      - ./database:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception