services:
  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
      - db_data:/var/www/html
    restart: always
  static-site:
    image: static-site
    build: requirements/bonus/static-site
    container_name: static-site
    ports:
      - "8080:8080"
    volumes:
      - static_data:/app/data
    networks:
      - inception
    restart: on-failure
  ftp:
    image: ftp
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
        - inception
    env_file:
      - ../secrets/credentials.txt
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: on-failure
  homepage:
    image: homepage
    build: requirements/bonus/homepage
    container_name: homepage
    networks:
      - inception
    ports:
      - "3000:3000"
    restart: on-failure
  adminer:
    image: adminer
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - db_data:/var/www/html
    restart: on-failure
  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
      - .env
    volumes:
      - db_data:/var/www/html
    restart: on-failure
  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    expose:
      - "9000"
    env_file:
      - ../secrets/credentials.txt
      - ../secrets/db_password.txt
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: on-failure
  redis:
    image: redis
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    ports:
      - "6380:6380"
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress

networks:
  inception:
    name: inception

volumes:
  static_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/static_site
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/db
      o: bind
