services:
  nginx:
    build: requirements/mandatory/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: on-failure
  uptime-kuma:
    build: requirements/bonus/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime_data:/app/data
    networks:
      - inception
    restart: on-failure
  static-site:
    build: requirements/bonus/static-site
    container_name: static-site
    ports:
      - "8080:8080"
    volumes:
      - static_data:/app/data
    networks:
      - inception
    restart: on-failure
  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
        - inception
    volumes:
      - wordpress_data:/app/data
    restart: on-failure
  homepage:
    build: requirements/bonus/homepage
    container_name: homepage
    networks:
      - inception
    ports:
      - "3000:3000"
    volumes:
      - homepage_data:/app/
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    ports:
      - "8081:8030"
  mariadb:
    build: requirements/mandatory/mariadb
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/www/html
    restart: on-failure
  wordpress:
    build: requirements/mandatory/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: on-failure



networks:
  inception:
    name: inception

volumes:
  static_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/static_site
      o: bind
  uptime_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/uptime-kuma
      o: bind
  homepage_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/homepage
      o: bind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/adminer
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/db
      o: bind
