services:
  uptime-kuma:
    build: requirements/bonus/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime_data:/app/data
    networks:
      - inception
  static-site:
    build: requirements/bonus/static-site
    container_name: static-site
    ports:
      - "8080:8080"
    volumes:
      - static_data:/app/data
    networks:
      - inception
  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ftp_data:/app/data

networks:
  inception:
    name: inception

volumes:
  static_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/static_site
      o: bind
  uptime_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/uptime-kuma
      o: bind
  ftp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bapasqui/data/ftp
      o: bind
